package dev.stormery.dao;

import dev.stormery.model.Programs;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import javax.sql.DataSource;
import java.util.List;


/**
 * Created by Stormery on 2018-06-26.
 */

@Component
@Scope("prototype")
public class ProgramsDAOSpring implements ProgramsDAO {

    private final static String CREATE_TABLE = "CREATE TABLE IF NOT EXISTS programs(ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY," +
            "NAME VARCHAR(255),DISK_SPACE INTEGER, COMPILATION_TIME INTEGER, INSTALL_TIME DOUBLE, DELAY DOUBLE, PROGRAM_LEVEL INTEGER, STRENGTH INTEGER, PRICE INTEGER, AMOUNT INTEGER)";
    private final static String INSERT_PROGRAM = "INSERT INTO programs (NAME,DISK_SPACE,COMPILATION_TIME,INSTALL_TIME,DELAY,PROGRAM_LEVEL,STRENGTH,PRICE,AMOUNT) VALUES(?,?,?,?,?,?,?,?,?)";
    private final static String UPDATE_PROGRAM = "UPDATE programs SET NAME = ?, DISK_SPACE = ?, COMPILATION_TIME = ?, INSTALL_TIME = ?, DELAY = ?, PROGRAM_LEVEL = ?," +
                                                "STRENGTH = ?, PRICE = ?, AMOUNT = ? WHERE ID=?";
    private final static String GET_ALL_PROGRAMS = "SELECT * FROM programs";

    private static Logger log = Logger.getLogger(ProgramsDAOSpring.class);

    /**
     * Spring component to manage JDBC operations
     */
    private JdbcTemplate jdbcTemplate;


    /**
     * Data source is injected from spring-config.xml via configuration with component-scan
     * https://docs.spring.io/spring/docs/4.2.x/spring-framework-reference/html/jdbc.html
     *
     * @param dataSource - Springs connection to database
     */
    @Autowired
    public void setDataSource(DataSource dataSource) {
        this.jdbcTemplate = new JdbcTemplate(dataSource);
    }


    public void init() {
        jdbcTemplate.execute(CREATE_TABLE);
    }

    /**
     * Saves or update program in the list<br>
     * If ID is provided by future implementation - it will update selected row
     * if ID is not given from implementation - it mean that we want to add new row
     */
    @Transactional
    public void save(Programs p) {
        if(p ==null){
            throw new RuntimeException("Program is empty");
        }
        if(p.getId() == null){
            jdbcTemplate.update(INSERT_PROGRAM, new Object[]{p.getName(),p.getDiskSpace(),p.getCompilationTime(),p.getInstallTime(),p.getDelay(),p.getProgramLevel(),
                    p.getStrength(),p.getPrice(),p.getAmount()});
        }else{
            jdbcTemplate.update(UPDATE_PROGRAM, new Object[]{p.getName(),p.getDiskSpace(),p.getCompilationTime(),p.getInstallTime(),p.getDelay(),p.getProgramLevel(),
                    p.getStrength(),p.getPrice(),p.getAmount(),p.getId()});
        }

        log.debug("Program added/updated in the list");
    }

    public List<Programs> getAll() {
        log.debug("Return all programs from db");
        return jdbcTemplate.query(GET_ALL_PROGRAMS, new ProgramsRowMapper());
    }


    @Transactional
    public void dummySave(){
        jdbcTemplate.update(INSERT_PROGRAM, new Object[]{"Test",1,1,3.0,1.0,1,1,1,1} );
    }
}
